language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.3

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_8a456a50c6bb_key -iv $encrypted_8a456a50c6bb_iv -in keystore.jks.enc -out keystore.jks -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew

script:
  - "./gradlew clean build check"

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file: RunnersCalculator.apk
  file_glob: true
  api_key:
    secure: gGGB57bLtvUJzEhenRYGmfEOsCrO3rhJD7qz0HshHvMS/HVgMIOX8XTYuO0P0XWb34KpBbpDnW6STQbRpCqfgCVT/2JseaVbJJ1VigUuUPv/Szfa3IzlXeKE3VXRnGrkQd/mr+fIMLc9gLXQmXfR7EwzRNnyeH+suknxHcFyvRZ0/9p7jHvwS1OEZ/6F53X0wcF9Snz5iQvcG5/+UlkvMNVEx5y7SZrAL9jUqHjKlnNOhQxEflebA0jB19hLfpgyFb2AMgkQdSl/ZYW3nWHLJ6HRjt7T5L8SwXScAU/0MjMyWpON/xJdWQkxXv+TKQZ5I8dcPrR0IU7RmnE+5N0MHnrFRcmyeluI/UnGT6VyEQ1cHtosLi5q+YZzjAkdGW7zVqpUzq3egFHyz22vwPZx2NpZMn51PTz52mhPDtWJWZoEoqkf3G1An1K81TJ5BgAKhNyvmolrIC+KAcm5ByV2mX5IDFVOMEJi158brh/u8PLOA2YgCFCQvKNTBiKw+WTnRxDapA1Xui18xMcaQdJCNMh1T7kEB4sRgklkrsDyK4iMW/H7J8H/BTZEz7Xtcb8JbeUf9uLIRcOwGH6WhmlDwDliQhzi/mmEOgRPLdb2RZ0yqZBYwmUE9C9/T9ObkyHBir6n7DmfEhyiL2DtZRPZXj0PqVtT3wQnY2GfHDOjqFI=
  on:
    repo: rnyholm/runcalc
    tags: true