language: android
sudo: required
jdk: oraclejdk8

env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_TOOLS=28.0.3
  - secure: Hgocn/gNdI8VvHXKPS5lAbhxkQclsBfcymV/RDkIZbNvbkI1uEPL4SMWVJ1nXkX37BbvBfVRm5FgIycc8n18qAWeRZiam4hXBdPkk3neYC9nve4T4k1tYbxLvdwD2Jk1+4lJN0uZ5ppZJYrNwx4FWEnSVV9yEwY7ld5e77D5MST7TnDsDu/dsG9u87o6XV9nA1nKZ8zvd1L/S0bdUAeZGIzS0eVwWALtGXAumcqKUKRIjoqq2cIrhJiYC1ThH3qiBJx/cFhiKJCiDKJdDN3PWm5Ec8czNhonywUyWEev8mz5TYJ/ERsAI7X1tq6YGEqQQx5RAIgwJzd087FFEN+yFmarkFhx7u5zN4paL5bQQlzpH/c42vuRYb1UL7Akk2gl60j2FcX5WDfYLSpgqRU70qHQd1KPnXB2bOcny8eHxNWEr4O573osfUuVtIGMQUQfJL279YR4RRYBizUKzk7ezxu6z+uFaKppzWAYYar2ZbbhFyAOu5YQ+Ub4V/H8EnhRAXk9HQBwnBgZM5cPw7VW6qlVuaz1kbae4EPXD4pzM5Mzh/q5Ku8Ejfez2ut1dRAz354w5TDWKrNKOEh3Ip36tb/ZL/LIrLjYStxY2i7i/Yj5BMDLWEYCl9cigeoxdWik1/smXyyqip8IfPEWeSwTvtmRrThvYbV0y7vIzchTe+Y=
  - secure: AMQjQiWOIDuGhjc5x2jna93mfYhMI/oXSIsg+7Dpi7fpyVh8aCJDL16xZ979UtfuiAvqJm8tbi13wxk483SvyYpNLfauPGdtWeC4kUPWu9a2NzIsIQrQG2COXNzPNH1aru7kuBMLWN8VnV9pHIpOyiDOc/eEHremwvVj9klwARfhAuwB8xED4Y26iRlaQbnPdwTvKQ1tQOU5RXDGvCuitggtm5easHqc5sBQVSTA0v3jUZRGpfda7ltyPhHEF+Gbw4p79rw2gCWRM/Um85DUqy/HPgxB1KHbSPIrT92KrR0aZkIhZMB4Cb8+bkNM6mE2EOUjDDv66Y+RQd2bqx+1/psI6NWcL2G2LEJZ6BmGdrll0LSgWv74ego5mFg57lSb6GXoF9+0tVQS5MjKh1Vz0PAWwQX+bWBBTHI+LPfG8HMoFyGXWYH+FPfUSuUQioE5tyDigzHgc7XqK9BxjPex7nDLwFqFN0K9lngRIZCsgjpONR47yruLbzABye7fL6To30zOBGr1sECPbFTksTDZ7gd7TcDFTaawXzHKG2sqY3WAxRtt9H1b+co6p6NGFVD6KPvSDhAktJb99Zo+PiCXETcLYAM4DqaRCi0d5Nrtf8+gCBFj6f3jZvXLebBxJNaDwK0X36M0IfnAy12h0HhOSPw0xLLyKlBRp94JyEkQRY0=

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    -
before_install:
  - openssl aes-256-cbc -K $encrypted_8a456a50c6bb_key -iv $encrypted_8a456a50c6bb_iv - in keystore.jks.enc -out keystore.jks -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  -
script:
  - "./gradlew clean build check"

before_deploy:
  - cp $TRAVIS_BUILD_DIR/.keystore $HOME
  - cd app/build/outputs/apk/
  - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk runcal

  # Verification
  - jarsigner -verify app-release-unsigned.apk
  - "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk RunnersCalculator.apk"

deploy:
  provider: releases
  file: RunnersCalculator.apk
  skip_cleanup: true
  on:
    repo: rnyholm/runcalc
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "gGGB57bLtvUJzEhenRYGmfEOsCrO3rhJD7qz0HshHvMS/HVgMIOX8XTYuO0P0XWb34KpBbpDnW6STQbRpCqfgCVT/2JseaVbJJ1VigUuUPv/Szfa3IzlXeKE3VXRnGrkQd/mr+fIMLc9gLXQmXfR7EwzRNnyeH+suknxHcFyvRZ0/9p7jHvwS1OEZ/6F53X0wcF9Snz5iQvcG5/+UlkvMNVEx5y7SZrAL9jUqHjKlnNOhQxEflebA0jB19hLfpgyFb2AMgkQdSl/ZYW3nWHLJ6HRjt7T5L8SwXScAU/0MjMyWpON/xJdWQkxXv+TKQZ5I8dcPrR0IU7RmnE+5N0MHnrFRcmyeluI/UnGT6VyEQ1cHtosLi5q+YZzjAkdGW7zVqpUzq3egFHyz22vwPZx2NpZMn51PTz52mhPDtWJWZoEoqkf3G1An1K81TJ5BgAKhNyvmolrIC+KAcm5ByV2mX5IDFVOMEJi158brh/u8PLOA2YgCFCQvKNTBiKw+WTnRxDapA1Xui18xMcaQdJCNMh1T7kEB4sRgklkrsDyK4iMW/H7J8H/BTZEz7Xtcb8JbeUf9uLIRcOwGH6WhmlDwDliQhzi/mmEOgRPLdb2RZ0yqZBYwmUE9C9/T9ObkyHBir6n7DmfEhyiL2DtZRPZXj0PqVtT3wQnY2GfHDOjqFI="