language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=28
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
#    - sys-img-armeabi-v7a-android-28
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  # workaround.. see https://stackoverflow.com/questions/37615379/travis-ci-build-doesnt-work-with-android-constraint-layout/40144426#40144426
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew

before_script:
#  - android list targets # list all targets
#  - echo no | android create avd --force -n test -t "android-28"
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - sleep 180
#  - adb devices
#  - adb shell input keyevent 82 &

script:
  - "./gradlew clean build check"
#  - "./gradlew clean build connectedCheck" # connectedCheck executes instrumentation tests located in src/androidTests