name: Release build

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Decode keystore
      env: 
            ENCODED_STRING: ${{ secrets.KEYSTORE }}
      run: |
            TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
            mkdir "${TMP_KEYSTORE_FILE_PATH}"
            echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/runcalc.jks

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean build check assembleRelease
      env: 
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Build Artifacts
        path: app/build/outputs/

    - name: Upload apk to release
      if: github.event_name == 'release'
      uses: svenstaro/upload-release-action@2.7.0

      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: app/build/outputs/apk/release/*release.apk
        tag: ${{ github.ref }}
        body: ""
        overwrite: true
        file_glob: true
